# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
 - openjdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN="d1ccdd17-a9c9-4ec6-9356-266db2df2a66"

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - freshman4000@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
