# используем язык java. Travis CI поддерживает другие языки тоже.
os: windows
language: java
jdk:
 - openjdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN="84a662ef-cf48-4c29-b579-f7eb3c0d2206"

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - freshman4000@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
